package com.cf.bsixapp.mbg.mapper;

import com.cf.bsixapp.mbg.model.BackRolePermissionRel;
import com.cf.bsixapp.mbg.model.BackRolePermissionRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BackRolePermissionRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    long countByExample(BackRolePermissionRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int deleteByExample(BackRolePermissionRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int insert(BackRolePermissionRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int insertSelective(BackRolePermissionRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    List<BackRolePermissionRel> selectByExampleWithRowbounds(BackRolePermissionRelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    List<BackRolePermissionRel> selectByExample(BackRolePermissionRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    BackRolePermissionRel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") BackRolePermissionRel record, @Param("example") BackRolePermissionRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByExample(@Param("record") BackRolePermissionRel record, @Param("example") BackRolePermissionRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByPrimaryKeySelective(BackRolePermissionRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByPrimaryKey(BackRolePermissionRel record);
}