package com.cf.bsixapp.mbg.mapper;

import com.cf.bsixapp.mbg.model.BackAdminPermissionrRel;
import com.cf.bsixapp.mbg.model.BackAdminPermissionrRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BackAdminPermissionrRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    long countByExample(BackAdminPermissionrRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int deleteByExample(BackAdminPermissionrRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int insert(BackAdminPermissionrRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int insertSelective(BackAdminPermissionrRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    List<BackAdminPermissionrRel> selectByExampleWithRowbounds(BackAdminPermissionrRelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    List<BackAdminPermissionrRel> selectByExample(BackAdminPermissionrRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    BackAdminPermissionrRel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") BackAdminPermissionrRel record, @Param("example") BackAdminPermissionrRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByExample(@Param("record") BackAdminPermissionrRel record, @Param("example") BackAdminPermissionrRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByPrimaryKeySelective(BackAdminPermissionrRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_permission_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByPrimaryKey(BackAdminPermissionrRel record);
}