package com.cf.bsixapp.mbg.mapper;

import com.cf.bsixapp.mbg.model.BackAdminRoleRel;
import com.cf.bsixapp.mbg.model.BackAdminRoleRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BackAdminRoleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_role_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    long countByExample(BackAdminRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_role_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int deleteByExample(BackAdminRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_role_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_role_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int insert(BackAdminRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_role_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int insertSelective(BackAdminRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_role_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    List<BackAdminRoleRel> selectByExampleWithRowbounds(BackAdminRoleRelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_role_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    List<BackAdminRoleRel> selectByExample(BackAdminRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_role_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    BackAdminRoleRel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_role_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") BackAdminRoleRel record, @Param("example") BackAdminRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_role_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByExample(@Param("record") BackAdminRoleRel record, @Param("example") BackAdminRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_role_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByPrimaryKeySelective(BackAdminRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin_role_rel
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByPrimaryKey(BackAdminRoleRel record);
}