package com.cf.bsixapp.mbg.mapper;

import com.cf.bsixapp.mbg.model.BackRole;
import com.cf.bsixapp.mbg.model.BackRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BackRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    long countByExample(BackRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int deleteByExample(BackRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int insert(BackRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int insertSelective(BackRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    List<BackRole> selectByExampleWithRowbounds(BackRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    List<BackRole> selectByExample(BackRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    BackRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") BackRole record, @Param("example") BackRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByExample(@Param("record") BackRole record, @Param("example") BackRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByPrimaryKeySelective(BackRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_role
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByPrimaryKey(BackRole record);
}