package com.cf.bsixapp.mbg.mapper;

import com.cf.bsixapp.mbg.model.BackAdmin;
import com.cf.bsixapp.mbg.model.BackAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BackAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    long countByExample(BackAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int deleteByExample(BackAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int insert(BackAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int insertSelective(BackAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    List<BackAdmin> selectByExampleWithRowbounds(BackAdminExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    List<BackAdmin> selectByExample(BackAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    BackAdmin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") BackAdmin record, @Param("example") BackAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByExample(@Param("record") BackAdmin record, @Param("example") BackAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByPrimaryKeySelective(BackAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByPrimaryKey(BackAdmin record);
}