package com.cf.bsixapp.mbg.mapper;

import com.cf.bsixapp.mbg.model.BackPermission;
import com.cf.bsixapp.mbg.model.BackPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BackPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_permission
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    long countByExample(BackPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_permission
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int deleteByExample(BackPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_permission
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_permission
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int insert(BackPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_permission
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int insertSelective(BackPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_permission
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    List<BackPermission> selectByExampleWithRowbounds(BackPermissionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_permission
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    List<BackPermission> selectByExample(BackPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_permission
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    BackPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_permission
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") BackPermission record, @Param("example") BackPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_permission
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByExample(@Param("record") BackPermission record, @Param("example") BackPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_permission
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByPrimaryKeySelective(BackPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_permission
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    int updateByPrimaryKey(BackPermission record);
}