package com.cf.bsixapp.mbg.mapper;

import com.cf.bsixapp.mbg.model.BSixBackAdmin;
import com.cf.bsixapp.mbg.model.BSixBackAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BSixBackAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    long countByExample(BSixBackAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    int deleteByExample(BSixBackAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    int insert(BSixBackAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    int insertSelective(BSixBackAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    List<BSixBackAdmin> selectByExampleWithRowbounds(BSixBackAdminExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    List<BSixBackAdmin> selectByExample(BSixBackAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    BSixBackAdmin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") BSixBackAdmin record, @Param("example") BSixBackAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    int updateByExample(@Param("record") BSixBackAdmin record, @Param("example") BSixBackAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    int updateByPrimaryKeySelective(BSixBackAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsix_back_admin
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    int updateByPrimaryKey(BSixBackAdmin record);
}