server:
  port: 8887

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bsix?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.cf.bsixapp.mbg.model
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

