package com.cf.bsixapp.mbg.model;

public class BackAdminRoleRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin_role_rel.id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin_role_rel.admin_id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    private Long adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin_role_rel.role_id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin_role_rel.id
     *
     * @return the value of bsix_back_admin_role_rel.id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin_role_rel.id
     *
     * @param id the value for bsix_back_admin_role_rel.id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin_role_rel.admin_id
     *
     * @return the value of bsix_back_admin_role_rel.admin_id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin_role_rel.admin_id
     *
     * @param adminId the value for bsix_back_admin_role_rel.admin_id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin_role_rel.role_id
     *
     * @return the value of bsix_back_admin_role_rel.role_id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin_role_rel.role_id
     *
     * @param roleId the value for bsix_back_admin_role_rel.role_id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}