package com.cf.bsixapp.mbg.model;

public class BackAdminPermissionrRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin_permission_rel.id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin_permission_rel.admin_id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    private Long adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin_permission_rel.permission_id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    private Long permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin_permission_rel.id
     *
     * @return the value of bsix_back_admin_permission_rel.id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin_permission_rel.id
     *
     * @param id the value for bsix_back_admin_permission_rel.id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin_permission_rel.admin_id
     *
     * @return the value of bsix_back_admin_permission_rel.admin_id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin_permission_rel.admin_id
     *
     * @param adminId the value for bsix_back_admin_permission_rel.admin_id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin_permission_rel.permission_id
     *
     * @return the value of bsix_back_admin_permission_rel.permission_id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin_permission_rel.permission_id
     *
     * @param permissionId the value for bsix_back_admin_permission_rel.permission_id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }
}