package com.cf.bsixapp.mbg.model;

import java.util.Date;

public class BackRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_role.id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_role.role_name
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_role.role_desc
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    private String roleDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_role.role_code
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_role.create_time
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_role.update_time
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_role.status
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_role.order_seq
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    private Integer orderSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_role.id
     *
     * @return the value of bsix_back_role.id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_role.id
     *
     * @param id the value for bsix_back_role.id
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_role.role_name
     *
     * @return the value of bsix_back_role.role_name
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_role.role_name
     *
     * @param roleName the value for bsix_back_role.role_name
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_role.role_desc
     *
     * @return the value of bsix_back_role.role_desc
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_role.role_desc
     *
     * @param roleDesc the value for bsix_back_role.role_desc
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_role.role_code
     *
     * @return the value of bsix_back_role.role_code
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_role.role_code
     *
     * @param roleCode the value for bsix_back_role.role_code
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_role.create_time
     *
     * @return the value of bsix_back_role.create_time
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_role.create_time
     *
     * @param createTime the value for bsix_back_role.create_time
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_role.update_time
     *
     * @return the value of bsix_back_role.update_time
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_role.update_time
     *
     * @param updateTime the value for bsix_back_role.update_time
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_role.status
     *
     * @return the value of bsix_back_role.status
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_role.status
     *
     * @param status the value for bsix_back_role.status
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_role.order_seq
     *
     * @return the value of bsix_back_role.order_seq
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public Integer getOrderSeq() {
        return orderSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_role.order_seq
     *
     * @param orderSeq the value for bsix_back_role.order_seq
     *
     * @mbg.generated Sat Apr 18 12:11:39 CST 2020
     */
    public void setOrderSeq(Integer orderSeq) {
        this.orderSeq = orderSeq;
    }
}