package com.cf.bsixapp.mbg.model;

import java.util.Date;

public class BSixBackAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin.id
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin.username
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin.password
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin.icon
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin.email
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin.nick_name
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin.remark
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin.create_time
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin.login_time
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsix_back_admin.status
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin.id
     *
     * @return the value of bsix_back_admin.id
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin.id
     *
     * @param id the value for bsix_back_admin.id
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin.username
     *
     * @return the value of bsix_back_admin.username
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin.username
     *
     * @param username the value for bsix_back_admin.username
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin.password
     *
     * @return the value of bsix_back_admin.password
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin.password
     *
     * @param password the value for bsix_back_admin.password
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin.icon
     *
     * @return the value of bsix_back_admin.icon
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin.icon
     *
     * @param icon the value for bsix_back_admin.icon
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin.email
     *
     * @return the value of bsix_back_admin.email
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin.email
     *
     * @param email the value for bsix_back_admin.email
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin.nick_name
     *
     * @return the value of bsix_back_admin.nick_name
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin.nick_name
     *
     * @param nickName the value for bsix_back_admin.nick_name
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin.remark
     *
     * @return the value of bsix_back_admin.remark
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin.remark
     *
     * @param remark the value for bsix_back_admin.remark
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin.create_time
     *
     * @return the value of bsix_back_admin.create_time
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin.create_time
     *
     * @param createTime the value for bsix_back_admin.create_time
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin.login_time
     *
     * @return the value of bsix_back_admin.login_time
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin.login_time
     *
     * @param loginTime the value for bsix_back_admin.login_time
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsix_back_admin.status
     *
     * @return the value of bsix_back_admin.status
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsix_back_admin.status
     *
     * @param status the value for bsix_back_admin.status
     *
     * @mbg.generated Sun Apr 12 11:45:38 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}